# Generated by Django 6.0.2 on 2026-02-16 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código/Placa')),
                ('tipo', models.CharField(choices=[('LAPTOP', 'Laptop'), ('PC', 'Computador de escritorio'), ('MONITOR', 'Monitor'), ('IMPRESORA', 'Impresora'), ('SWITCH', 'Switch'), ('ROUTER', 'Router'), ('SERVER', 'Servidor'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(max_length=100)),
                ('fecha_compra', models.DateField()),
                ('valor_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('garantia_meses', models.IntegerField(default=12, help_text='Meses de garantía')),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True)),
                ('factura', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Factura')),
                ('especificaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.categoria')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_creados', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.estado')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.marca')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Responsable actual')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.ubicacion')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['codigo'], name='inventario__codigo_77b424_idx'), models.Index(fields=['serial'], name='inventario__serial_d3d662_idx'), models.Index(fields=['estado'], name='inventario__estado__e076ec_idx')],
            },
        ),
    ]
