# Generated by Django 6.0.2 on 2026-02-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='especificaciones',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
