# Generated by Django 6.0.2 on 2026-02-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código/Inventario'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activo',
            name='garantia_meses',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='activo',
            name='tipo',
            field=models.CharField(choices=[('LAPTOP', 'Laptop'), ('PC', 'Computador de escritorio'), ('MONITOR', 'Monitor'), ('IMPRESORA', 'Impresora'), ('SWITCH', 'Switch'), ('ROUTER', 'Router'), ('SERVER', 'Servidor'), ('CELULAR', 'Celular'), ('OTRO', 'Otro')], default='OTRO', max_length=20),
        ),
    ]
