# Generated by Django 6.0.2 on 2026-02-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_activo_especificaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='especificaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
