# Generated by Django 6.0.2 on 2026-03-02 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_activo_tipo'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activo',
            name='inventario__serial_d3d662_idx',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='serial',
        ),
    ]
