# Generated by Django 6.0.2 on 2026-03-02 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_sede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='descripcion',
        ),
    ]
