"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from django.core.exceptions import ImproperlyConfigured
from decouple import config
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Crear directorio de logs si no existe
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY") or config("SECRET_KEY", default=None)
if not SECRET_KEY:
    raise ImproperlyConfigured("SECRET_KEY is not set. Define it in environment or .env")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = str(config("DEBUG", default="False")).lower() in ["true", "1", "yes"]

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="*").split(",")
CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default="http://localhost:8000,http://127.0.0.1:8000"
).split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'crispy_forms',
    'crispy_bootstrap5',
    'axes',
    
    # Local apps
    'accounts',
    'core',
    'inventario',
    'asignaciones',
    'movimientos',
    'catalogos',
    'reportes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
    'accounts.middleware.SessionTimeoutMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database - PostgreSQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 10,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'accounts.validators.UppercaseValidator',
    },
    {
        'NAME': 'accounts.validators.SpecialCharacterValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Bogota'  # Ajusta según tu país

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)

STATIC_URL = '/static_inventario/'
STATIC_ROOT = BASE_DIR / "staticfiles_inventario"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Login URLs
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'core:dashboard'
LOGOUT_REDIRECT_URL = 'accounts:login'

# Timeout de sesión por inactividad
SESSION_INACTIVITY_TIMEOUT = 1800  # 30 minutos
# Tiempo de vida de la cookie de sesión (2 horas)
SESSION_COOKIE_AGE = 7200
# Guardar la sesión en cada solicitud para actualizar el tiempo de inactividad
SESSION_SAVE_EVERY_REQUEST = True

# ============================================================================
# CONFIGURACIÓN DE SEGURIDAD
# ============================================================================

# --- Cookies de sesión seguras ---
SESSION_COOKIE_HTTPONLY = True       # Impide acceso a la cookie desde JavaScript
SESSION_COOKIE_SAMESITE = 'Lax'     # Protección contra CSRF en cookies
SESSION_COOKIE_SECURE = not DEBUG    # Solo HTTPS en producción
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Sesiones en base de datos

# --- Cookie CSRF segura ---
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = not DEBUG

# --- Headers de seguridad HTTP ---
SECURE_BROWSER_XSS_FILTER = True            # Activa filtro XSS del navegador
SECURE_CONTENT_TYPE_NOSNIFF = True           # Previene MIME-type sniffing
X_FRAME_OPTIONS = 'DENY'                    # Previene clickjacking (iframe)
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# --- HTTPS en producción ---
if not DEBUG:
    SECURE_SSL_REDIRECT = True               # Redirige HTTP → HTTPS
    SECURE_HSTS_SECONDS = 31536000           # 1 año de HSTS
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# --- Backends de autenticación (axes + Django) ---
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# ============================================================================
# DJANGO-AXES — Protección contra fuerza bruta
# ============================================================================
AXES_FAILURE_LIMIT = 5                      # Bloquear después de 5 intentos fallidos
AXES_COOLOFF_TIME = 0.5                     # Bloqueo de 30 minutos (en horas)
AXES_LOCK_OUT_AT_FAILURE = True             # Activar bloqueo
AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']  # Bloquear por nombre de usuario e IP
AXES_RESET_ON_SUCCESS = True                # Resetear conteo al iniciar sesión correctamente
AXES_ENABLE_ACCESS_FAILURE_LOG = True       # Log de intentos fallidos
AXES_LOCKOUT_CALLABLE = 'accounts.views.axes_lockout_view'  # Vista personalizada de bloqueo

# --- Logging de seguridad ---
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'security': {
            'format': '[{asctime}] SEGURIDAD {levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {        'security_file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': str(BASE_DIR / 'logs' / 'security.log'),
            'formatter': 'security',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'security',
        },
    },
    'loggers': {
        'axes': {
            'handlers': ['security_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['security_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}