# Generated by Django 5.2 on 2025-04-29 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la dependencia')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Computador', 'Computador'), ('Impresora', 'Impresora'), ('Proyector', 'Proyector')], max_length=50, verbose_name='Tipo de equipo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('serial', models.CharField(max_length=100, unique=True, verbose_name='Número de serie')),
                ('especificaciones', models.TextField(verbose_name='Especificaciones')),
                ('asignado_a', models.CharField(blank=True, max_length=100, verbose_name='Asignado a')),
                ('fecha_compra', models.DateField(blank=True, null=True, verbose_name='Fecha de compra')),
                ('fecha_instalacion', models.DateField(blank=True, null=True, verbose_name='Fecha de instalación')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['tipo', 'marca', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la sede')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CambioParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(max_length=100, verbose_name='Componente')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_cambio', models.DateField(verbose_name='Fecha del cambio')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='equipos.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Cambio de Parte',
                'verbose_name_plural': 'Cambios de Partes',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del salón')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.dependencia', verbose_name='Dependencia')),
            ],
            options={
                'verbose_name': 'Salón',
                'verbose_name_plural': 'Salones',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipos.salon', verbose_name='Salón'),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.sede', verbose_name='Sede'),
        ),
    ]
