# Generated by Django 6.0.2 on 2026-02-16 04:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaciones', '0001_initial'),
        ('catalogos', '0001_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada a inventario'), ('SALIDA', 'Salida de inventario'), ('ASIGNACION', 'Asignación a usuario'), ('DEVOLUCION', 'Devolución'), ('TRASLADO', 'Traslado de ubicación'), ('REPARACION', 'Envío a reparación'), ('BAJA', 'Dar de baja'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('ACTUALIZACION', 'Actualización de datos')], max_length=20)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.activo')),
                ('asignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='asignaciones.asignacion')),
                ('estado_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_estado_destino', to='catalogos.estado')),
                ('estado_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_estado_origen', to='catalogos.estado')),
                ('responsable_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_responsable_anterior', to=settings.AUTH_USER_MODEL)),
                ('responsable_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_responsable_nuevo', to=settings.AUTH_USER_MODEL)),
                ('ubicacion_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='catalogos.ubicacion')),
                ('ubicacion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='catalogos.ubicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['fecha'], name='movimientos_fecha_54633e_idx'), models.Index(fields=['activo', 'fecha'], name='movimientos_activo__fd9b79_idx'), models.Index(fields=['tipo'], name='movimientos_tipo_30ba9d_idx')],
            },
        ),
    ]
