# Generated by Django 6.0.2 on 2026-02-15 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0001_initial'),
        ('catalogos', '0001_initial'),
        ('inventario', '0003_alter_activo_especificaciones'),
        ('movimientos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada a inventario'), ('SALIDA', 'Salida de inventario'), ('ASIGNACION', 'Asignación a usuario'), ('DEVOLUCION', 'Devolución'), ('TRASLADO', 'Traslado de ubicación'), ('REPARACION', 'Envío a reparación'), ('BAJA', 'Dar de baja'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('ACTUALIZACION', 'Actualización de datos')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['tipo'], name='movimientos_tipo_30ba9d_idx'),
        ),
    ]
