# Generated by Django 6.0.2 on 2026-02-16 04:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_estimada_devolucion', models.DateTimeField(blank=True, help_text='Fecha estimada de devolución', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, help_text='Motivo de la asignación', max_length=200, null=True)),
                ('activo_actual', models.BooleanField(default=True, help_text='Indica si esta es la asignación actual')),
                ('activo_devuelto', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='inventario.activo')),
                ('asignado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('usuario_asignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'ordering': ['-fecha_asignacion'],
                'indexes': [models.Index(fields=['activo', 'activo_actual'], name='asignacione_activo__260694_idx'), models.Index(fields=['usuario_asignado', 'activo_actual'], name='asignacione_usuario_8c68a0_idx'), models.Index(fields=['fecha_asignacion'], name='asignacione_fecha_a_d48847_idx')],
            },
        ),
    ]
