# Generated by Django 6.0.2 on 2026-02-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='evidencias',
            field=models.URLField(blank=True, help_text='URL de evidencia fotográfica o documental (Google Drive, OneDrive, etc.)', max_length=500, null=True, verbose_name='Evidencias'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_estimada_devolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='motivo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
