# Generated by Django 6.0.2 on 2026-03-02 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0002_asignacion_evidencias_and_more'),
        ('catalogos', '0003_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.sede', verbose_name='Sede'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.ubicacion', verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='evidencias',
            field=models.URLField(blank=True, help_text='URL de evidencia fotográfica o documental', max_length=500, null=True, verbose_name='Evidencias'),
        ),
    ]
